카카오 로그인
nolmungshemung/writing-hub pull request #47
Opened 2022-02-10 02:40 UTC by JuHyerin

### Short description

`next-auth`를 이용한 카카오 로그인

### Proposed changes

- next auth 설정 
    - 카카오 key
    - 커스텀 로그인 페이지로 이동 
- Header 로그인 버튼 -> writing hub 로그인 페이지
- writing hub 로그인 페이지의 로그인 버튼 -> 카카오 로그인 페이지

### How to test (Optional)

1. `.env` 파일의 `stage=prod`
2. 프로그램 실행
3. http://localhost:3000
4. 헤더 로그인 버튼 클릭하여 로그인 진행
5. 헤더 로그아웃 버튼 클릭하여 로그아웃 진행

_Closes #36

2022-02-10 03:22 UTC, akariyan commented
로그인 시도하면 http://localhost:3000/login?callbackUrl=http://localhost:3000/&error=OAuthSignin로 주소만 바뀌고 로그인은 안되는데 무슨 문제일까요? 팝업 허용도 해놨고 콘솔에는 아무런 내용이 안뜨네요

2022-02-10 03:22 UTC, ppark2ya commented on components/layout/Header.tsx
> +          </HeaderButton>
제가 주석 쳐놓은거에 `내피드`도 있는데 로그아웃 옆에 보이도록 해주시고 주석 지워주세요~ 필명 등록은 필요없는듯..

2022-02-10 03:22 UTC, ppark2ya commented on pages/login.tsx
> +    signIn('kakao', { callbackUrl });
urlParam에 어떤값이 들어오는거에요??
`KAKAO_REDIRECT_URI`에 있는 callbackUrl인가???
`signIn(ANY_PROVIDER, { callbackUrl: redirectUrl })` 이 실행되면 카카오 로그인이 실행되고 성공하면 callbackUrl로 돌아오는 식인건가요?

2022-02-10 03:22 UTC, ppark2ya commented on pages/_app.tsx
> +          </SessionProvider>
지금대로면 로그인했을 때 세션이 계속 유지되는건가요?? 만약 그렇다면 로그인 시간을 제한하는 코드가 있으면 좋을 것 같아요. 15~30분 정도로?
https://next-auth.js.org/getting-started/upgrade-v4#sessionprovider

2022-02-10 03:22 UTC, ppark2ya commented on components/layout/Header.tsx
> +          </HeaderButton>
`login.tsx`의 signIn과 여기의 signIn의 사용법이 다른 이유가 뭐에요??

2022-02-10 03:22 UTC, ppark2ya commented on pages/api/auth/[...nextauth].ts
> +});
나중에 필요하면 useSession을 통해 가져온 데이터의 형태를 수정할 필요도 있을거 같은데 참고만 해보세용
https://next-auth.js.org/v3/getting-started/typescript#main-module
https://next-auth.js.org/configuration/callbacks

2022-02-10 03:27 UTC, ppark2ya commented
> 로그인 시도하면 [http://localhost:3000/login?callbackUrl=http://localhost:3000/&error=OAuthSignin로](http://localhost:3000/login?callbackUrl=http://localhost:3000/&error=OAuthSignin%EB%A1%9C) 주소만 바뀌고 로그인은 안되는데 무슨 문제일까요? 팝업 허용도 해놨고 콘솔에는 아무런 내용이 안뜨네요

.env에 필요한 값을 안넣어서 그런듯?

2022-02-10 03:30 UTC, ppark2ya commented on components/layout/Header.tsx
> +          </HeaderButton>
헤더의 로그인 버튼을 눌렀을 땐 로그인 화면으로 이동시키는게 맞는 동작인듯??

2022-02-10 03:31 UTC, ppark2ya commented on components/layout/Header.tsx
> +          </HeaderButton>
그리고 로그인 성공했는데 로그아웃 버튼으로 안바뀌는거 같은데 확인 부탁드려용

2022-02-10 03:35 UTC, JuHyerin commented on components/layout/Header.tsx
> +          </HeaderButton>
next auth의 signIn 함수의 첫번째 파라미터는 provider name을 지정하여 해당 provider의 로그인 페이지로 이동합니다. 
첫번째 파라미터를 지정하지 않을 경우, `[...nextauth].ts`에 지정한 로그인 페이지로 이동합니다

2022-02-10 03:36 UTC, JuHyerin commented on components/layout/Header.tsx
> +          </HeaderButton>
헤더의 로그인이었던 버튼이 로그아웃으로 바뀌지 않는다는 말씀이신가요??

2022-02-10 03:47 UTC, akariyan commented on components/layout/Header.tsx
> +          </HeaderButton>
저는 로그인 로그아웃 버튼 잘 바뀌네요

2022-02-10 03:51 UTC, akariyan approved these changes

2022-02-10 04:21 UTC, ppark2ya commented on components/layout/Header.tsx
> +          </HeaderButton>
아 msw 키고봤었네요 ㅋㅋ 로그아웃버튼으로 잘 바뀌넹

2022-02-10 04:51 UTC, JuHyerin commented
> 로그인 시도하면 [http://localhost:3000/login?callbackUrl=http://localhost:3000/&error=OAuthSignin로](http://localhost:3000/login?callbackUrl=http://localhost:3000/&error=OAuthSignin%EB%A1%9C) 주소만 바뀌고 로그인은 안되는데 무슨 문제일까요? ㅠㅠ팝업 허용은 해놨고 서버쪽 콘솔엔 이렇게 뜨네요 ![image](https://user-images.githubusercontent.com/39260956/153331365-8cc4d744-542f-4ae5-a494-0defafc9665b.png)

.env에 테스트 절차 1에 기재된 변수들을 정의하지 않아서 그런것 같아요. 
슬랙으로 종태님이 말씀해 주신 거 봤는데 지금은 해결되셨나요??

2022-02-10 06:41 UTC, JuHyerin commented on pages/login.tsx
> +    signIn('kakao', { callbackUrl });
헤더의 로그인 버튼을 누르면 next-auth의 signIn 함수로 인해 /login?callbackUrl=`현재페이지url` 로 로그인 버튼을 클릭할 때의 페이지 url과 함께 넘어옵니다.
예를 들어 글쓰기 페이지에서 로그인 버튼을 클릭하면 `http://localhost:3000/writing`이 넘어가게 됩니다.

2022-02-10 07:24 UTC, JuHyerin commented on pages/login.tsx
> +    signIn('kakao', { callbackUrl });
`KAKAO_REDIRECT_URI`는 사용되지 않아 PR 설명에서 제외했습니다.

2022-02-10 07:32 UTC, JuHyerin commented on pages/login.tsx
> +    signIn('kakao', { callbackUrl });
signIn(ANY_PROVIDER, { callbackUrl: redirectUrl }) 이 실행되면 카카오 로그인이 실행되고 성공하면 callbackUrl로 돌아오는 식인건가요?
>>넹

2022-02-10 07:34 UTC, ppark2ya commented on pages/login.tsx
> +    signIn('kakao', { callbackUrl });
일단 로그인페이지에서 카카오 로그인 버튼이 따로 있어서 헤더의 로그인 버튼을 클릭했을 땐 로그인 페이지로 이동하는 플로우가 맞는거 같아요

2022-02-10 07:42 UTC, JuHyerin commented on pages/login.tsx
> +    signIn('kakao', { callbackUrl });
`NEXTAUTH_URL=http://localhost3009/writing`으로 정의한 후 테스트해보니
https://kauth.kakao.com/oauth/authorize 호출 시 payload의 redirect_uri가 `http://localhost3009/writing/callback/kakao`로 넘어가는 것으로 보아 `NEXTAUTH_URL`/callback/kakao로 만들어서 보내지나봐요
공부를 더 해야할 것 같아요;

2022-02-10 07:44 UTC, JuHyerin commented on pages/_app.tsx
> +          </SessionProvider>
`expires` 값으로 name, email이랑 같이 만료날짜를 받아오는데 기간이 한달인가봐요 따로 15분~30분으로 지정할까요?

2022-02-10 08:22 UTC, ppark2ya commented on pages/_app.tsx
> +          </SessionProvider>
네 15~30분 정도로 제한하는게 좋을거 같아요 1달동안 유지는 너무 긴거같아요

2022-02-10 12:27 UTC, ppark2ya commented on components/layout/Header.tsx
>            내피드
내 피드도 로그인 할 때 나와야 되요~ 로그인 한 유저의 피드를 보러 가는거라서

2022-02-14 08:42 UTC, ppark2ya requested changes

2022-02-14 08:42 UTC, ppark2ya commented on components/layout/Header.tsx
>            내피드
sessionData가 있을때 `필명등록/내피드` 가 나와야되요

2022-02-14 08:42 UTC, ppark2ya commented on components/layout/Header.tsx
> +  }, [sessionData]);
제가 의도한 바는 https://github.com/nextauthjs/next-auth/releases/tag/v4.0.0-next.12 이런식으로 SessionProvider에 
```typescript
 <Provider options={{clientMaxAge: 0, keepAlive: 0}}>{children}</Provider>
 <SessionProvider staleTime={0} refetchInterval={0}>{children}</SessionProvider> 
```
이었는데~ 일단 애매하면 해당 부분 지우고 나중에 고려해보죠

2022-02-14 09:31 UTC, JuHyerin commented on components/layout/Header.tsx
> +  }, [sessionData]);
음 첨부해주신 링크 확인해봤는데 세션을 다시 가져오는 타이밍을 부여하는 옵션만 있는 것 같아요.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/55668658/153837319-17fe3fc4-0cfe-49d7-b0c0-d34e567cb53b.png">

2022-02-14 09:53 UTC, ppark2ya submitted a review, later dismissed

2022-02-15 07:35 UTC, ppark2ya approved these changes

2022-02-15 09:36 UTC, merged