글읽기 페이지 개발
nolmungshemung/writing-hub pull request #52
Opened 2022-02-13 11:43 UTC by akariyan

### Short description

글읽기 페이지 개발

### Proposed changes

- 글읽기 페이지 API 연동
- 글읽기 페이지 퍼블리싱
- index 페이지에서 글읽기 페이지로 진입할 수 있도록 onCardClick 메소드 수정

### How to test (Optional)

http://localhost:3000/contents?contentsId=10

### Screenshots (Optional)

![image](https://user-images.githubusercontent.com/39260956/153751407-190722fa-932e-42b2-b9b6-b7e19add1c1e.png)

### Reference (Optional)

_Closes #49

2022-02-13 13:17 UTC, ppark2ya approved these changes

2022-02-13 13:17 UTC, ppark2ya commented on pages/contents.tsx
> +  console.log(data);
로그 삭제

2022-02-13 13:21 UTC, ppark2ya requested changes

2022-02-13 13:21 UTC, ppark2ya commented on pages/contents.tsx
> +  const onCardClick = (targetContentsId: number) => {
target보다는 `translatedContentsId`가 의미가 더 맞는듯

2022-02-13 13:21 UTC, ppark2ya commented on pages/contents.tsx
> +          >
사이즈를 calc 로 할게 아니라 %로 잡아야 될 듯. 지금 노트북 해상도에서 봤을 때 보기가 많이 안좋네

2022-02-14 08:44 UTC, JuHyerin commented on pages/contents.tsx
>    const contentsId = Number(router.query.contentsId);
/reading_contents?contents_id=`NaN`으로 호출되고 있어요

2022-02-14 11:54 UTC, akariyan commented on pages/contents.tsx
>    const contentsId = Number(router.query.contentsId);
번역글 클릭해서 이동할때 발생한 이슈 맞나요? 변수명 바꾸면서 발생한거라 확인하고 방금 해결했습니당

2022-02-14 12:40 UTC, ppark2ya approved these changes

2022-02-14 12:40 UTC, ppark2ya commented
수고하셨습니다

2022-02-14 12:43 UTC, merged